name: Feature request
description: Suggest an improvement or new feature.
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: idea
    attributes:
      label: Describe your idea
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered

  - type: textarea
    id: extra
    attributes:
      label: Additional information
